### PR TITLE
Cancelled networking when the search cancel button is pressed

### LINKED ISSUE #549: Cancel networking when cancelling search before the request completes
Steps to reproduce:

1. Search something
2. Tap cancel
3. The "Recent searches" are shown
4. The request finishes, and the view is replaced with the results

4 shouldn't happen when you cancelled already

### PR DESCRIPTION
**Pull request by heshamsalman**
Tested this through a throttled Charles Proxy to ensure network requests are indeed being cancelled. 

Closes #549

### CODE REVIEW

File: Classes/Search/GithubClient+Search.swift [hunk 1]
```diff
@@ -7,19 +7,26 @@
...
+        containerWidth: CGFloat,
+        completion: @escaping (SearchResultType) -> ()
+        ) -> Cancellable {
         let query = SearchReposQuery(search: query, before: before)
-        
-        fetch(query: query) { (result, error) in
-            guard error == nil, result?.errors == nil else {
+
+        return fetch(query: query) { (result, error) in
+            guard (error == nil || (error! as NSError).code == -999), result?.errors == nil else {
```
Comment (Sherlouk) [inline Classes/Search/GithubClient+Search.swift]: Could we refactor this slightly to drop the force unwrap? (I get that it's safe because of the nil check before, but would prefer not to have it if we can easily avoid it!)

File: Classes/Search/SearchViewController.swift [hunk 2]
```diff
@@ -101,12 +102,13 @@ SearchResultSectionControllerDelegate {
     func search(term: String) {
         recentStore.add(recent: term)
 
-        state = .loading
         update(animated: false)
 
-        client.search(query: term, containerWidth: view.bounds.width) { [weak self] resultType in
+        let request = client.search(query: term, containerWidth: view.bounds.width) { [weak self] resultType in
+            guard let state = self?.state, case .loading(_) = state else { return }
```
Comment (Sherlouk) [inline Classes/Search/SearchViewController.swift]: Do you still need the `(_)` here bit? I know in switches, if all parameters are unused you can just not specify them! `case .loading = state`

Comment (heshamsalman) [reply Classes/Search/SearchViewController.swift]: Good catch! 👍

File: Classes/Search/GithubClient+Search.swift (hunk 1 above)
Comment (heshamsalman) [reply Classes/Search/GithubClient+Search.swift]: @Sherlouk 
How do you feel about global-scope private functions? 

```swift
extension GitHubClient { 
  ...
  guard errorIsNilOrCancelled(error), ...
  ...
}

private func errorIsNilOrCancelled(_ error: Error?) -> Bool {
    guard let error = error else { return true }
    return (error as NSError).code == -999
}
```

Comment (Sherlouk) [reply Classes/Search/GithubClient+Search.swift]: I don't terribly mind this, alternatively just using optionals: `guard (error == nil || (error as? NSError)?.code == -999), result?.errors == nil else {` should have the same effect (I think)?

Leaving it up to you, as long as we have no pesky exclamation marks 😉

Comment (heshamsalman) [reply Classes/Search/GithubClient+Search.swift]: @Sherlouk I'd love to use an optional here but `Error?` doesn't bridge to `NSError` -- the compiler asks that we use a hard-cast `as!` for that conversion

File: Classes/Search/SearchViewController.swift [hunk 3]
```diff
@@ -186,10 +188,14 @@ SearchResultSectionControllerDelegate {
     }
 
     func searchBarCancelButtonClicked(_ searchBar: UISearchBar) {
+        if case let .loading(request) = state {
```
Comment (rnystrom) [inline Classes/Search/SearchViewController.swift]: TIL!
