### PR TITLE
Prevent SLKTextViewController cache from overwriting text

### LINKED ISSUE #1095: Comment image uploading broken when already typed something
To reproduce:

Start a comment
Upload an image

The image markdown is never added to your WIP comment

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.14.0 (1230)
Device: iPhone X (iOS 11.1.2)
TestFlight: true
</pre>
</details>

### PR DESCRIPTION
**Pull request by rnystrom**
@Sherlouk was spot on!

Fixes #1095

Also changing image insertion to be at the cursor

### CODE REVIEW

**Comment by BasThomas** [comment]
Oh ha, I should've assigned the issue. Was working on something similar.

Not sure if this would be exactly what we want in all situations? This is what I came up with:

```swift
self?.dismiss(animated: true) { [weak delegate = self?.delegate] in
    delegate?.imageUploaded(link: link, altText: name)
}
```

File: Classes/Views/TextActionsController.swift [hunk 1]
```diff
@@ -74,7 +74,7 @@ final class TextActionsController: NSObject,
     // MARK: ImageUploadDelegate
 
     func imageUploaded(link: String, altText: String) {
-        textView?.replace(left: "![\(altText)](\(link))", right: nil, atLineStart: true)
+        textView?.replace(left: "![\(altText)](\(link))", right: nil, atLineStart: false)
```
Comment (BasThomas) [inline Classes/Views/TextActionsController.swift]: Nice catch, saw this too and was going to ask.
