### PR TITLE
Log when prompting for rating

### LINKED ISSUE #1182: Add logging event when prompting for rating
Should add for both types. Can see how often they trigger (even if we don’t know for sure if the native one appears).

Maybe couple with how often the rating controller is _asked_ to prompt, that way we can see a ratio and frequency.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.15.0 (1512339646)
Device: iPhone X (iOS 11.1.2)
TestFlight: true
</pre>
</details>

### PR DESCRIPTION
**Pull request by rnystrom**
Fixes #1182

### CODE REVIEW

File: Classes/Systems/Rating/RatingController.swift [hunk 1]
```diff
@@ -57,10 +58,17 @@ final class RatingController {
     class func prompt(_ type: Prompt) {
         guard canPrompt(.system) else { return }
 
+        let typeString: String
         switch type {
-        case .system: requestSystem()
-        case .inFeed: openAppStore()
+        case .system:
+            typeString = "system"
```
Comment (BasThomas) [inline Classes/Systems/Rating/RatingController.swift]: What about adding these typeStrings to the enum itself?

Comment (rnystrom) [reply Classes/Systems/Rating/RatingController.swift]: Ugh that’s a way better idea. I’ll update.
