### PR TITLE
Disable the right item editing a comment to an empty one

### LINKED ISSUE #976: Add native error for empty comments (that are not root)
We should either show a local error toast containing the message (like with the empty title when creating an issue) (this might be fragile if GitHub changes this in the future though, allowing empty comments for some reason).

Or we can check if, based on the error code / headers, we can display something more useful to the user (instead of the generic "Something went wrong.")

### PR DESCRIPTION
**Pull request by BasThomas**
Fixes #976.

Followed the same thing we do when [creating a new issue](https://github.com/rnystrom/GitHawk/blob/master/Classes/New%20Issue/NewIssueTableViewController.swift#L202-L204).

### CODE REVIEW

File: Classes/Issues/EditComment/EditCommentViewController.swift [hunk 1]
```diff
@@ -164,4 +165,9 @@ class EditCommentViewController: UIViewController {
         ToastManager.showGenericError()
     }
 
+    func textViewDidChange(_ textView: UITextView) {
+        guard textView === self.textView else { return }
```
Comment (BasThomas) [inline Classes/Issues/EditComment/EditCommentViewController.swift]: Just as a sanity check in case we add another textview, but can remove if redundant.

Comment (rnystrom) [reply Classes/Issues/EditComment/EditCommentViewController.swift]: Ya bit redundant atm
