### PR TITLE
More expressive search placeholders

### LINKED ISSUE #968: Search tab search for placeholder says “Search GitHub”
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.13.0 (1191)
Device: iPhone X (iOS 11.1.1)
TestFlight: false
</pre>
</details>

### LINKED ISSUE #969: Bookmarks tab search for placeholder says “Search Bookmarks”
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.13.0 (1191)
Device: iPhone X (iOS 11.1.1)
TestFlight: false
</pre>
</details>

### PR DESCRIPTION
**Pull request by BasThomas**
Fixes #968 
Fixes #969 

This change does not touch the [repository search](https://github.com/rnystrom/GitHawk/blob/search-placeholders/Classes/Repository/RepositoryIssuesViewController.swift#L99); should that be "Search Repository"?

Also does not change the [3D Touch shortcut](https://github.com/rnystrom/GitHawk/blob/search-placeholders/Classes/Systems/ShortcutHandler.swift#L52); should that be "Search GitHub" too?

### CODE REVIEW

**Comment by rnystrom** [comment]
I think the shortcut is ok for now

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

File: Classes/Views/Constants.swift [hunk 1]
```diff
@@ -37,6 +37,8 @@ enum Constants {
         static let bullet = "\u{2022}"
         static let bulletHollow = "\u{25E6}"
         static let search = NSLocalizedString("Search", comment: "")
+        static let searchGitHub = "\(Constants.Strings.search) GitHub"
+        static let searchBookmarks = "\(Constants.Strings.search) \(Constants.Strings.bookmarks)"
```
Comment (rnystrom) [inline Classes/Views/Constants.swift]: Can we make these separate instead of composed? This wont work once localized.

Comment (BasThomas) [reply Classes/Views/Constants.swift]: What won't work once localized?

Comment (rnystrom) [reply Classes/Views/Constants.swift]: - "GitHub" is a plane string
- Most languages aren't just combos of words, "Search Bookmarks"
  - e.g. French, this translates to "rechercher des signets"
  - While doing them one-by-one in french, search is "chercher" and bookmarks is "signets", so combined is "chercher signets"

Comment (BasThomas) [reply Classes/Views/Constants.swift]: Makes sense. The `GitHub` being a plane string didn't really seem like an issue to me, as that doesn't change based on language. I'll change.

**Comment by BasThomas** [comment]
Should be good to go now!
