### PR TITLE
Make lock action destructive, Append issue type

### LINKED ISSUE #143: Lock/unlock issues and PRs

### LINKED ISSUE #557: Append “Issue” or “Pull Request” to Close action
Help reinforce what action is being taken

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (2013)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: false
</pre>
</details>

### PR DESCRIPTION
**Pull request by Sherlouk**
Closes #143
Closes #557

Got to keep PR count >= 10 😉

### CODE REVIEW

File: Classes/Issues/IssuesViewController.swift [hunk 1]
```diff
@@ -234,7 +234,7 @@ IssueCommentSectionControllerDelegate {
             status != .merged
             else { return nil }
         
-        return AlertAction.toggleIssue(status) { [weak self] _ in
+        return AlertAction.toggleIssue(status, issue: current?.status.pullRequest != true) { [weak self] _ in
```
Comment (BasThomas) [inline Classes/Issues/IssuesViewController.swift]: Wait, do we not have access to the `NotificationType` from here?

File: Classes/Utility/AlertAction.swift [hunk 2]
```diff
@@ -106,20 +106,24 @@ struct AlertAction {
         return UIAlertAction(title: NSLocalizedString("Discard", comment: ""), style: .destructive, handler: handler)
     }
     
-    static func toggleIssue(_ status: IssueStatus, handler: AlertActionBlock? = nil) -> UIAlertAction {
+    static func toggleIssue(_ status: IssueStatus, issue: Bool, handler: AlertActionBlock? = nil) -> UIAlertAction {
+        let issueType = issue ? "Issue" : "Pull Request"
```
Comment (BasThomas) [inline Classes/Utility/AlertAction.swift]: Probably safe to wrap these in `NSLocalizedString`?

Comment (Sherlouk) [reply Classes/Utility/AlertAction.swift]: No need as they're used in a NSLocalizedString directly beneath, if these were localized it would cause havoc down the line because you'd have

"Issue" = "**eisiúint**"
"Open **eisiúint**" = "Ceist oscailte" 

Which just over complicates things IMO

File: Classes/Issues/IssuesViewController.swift (hunk 1 above)
Comment (Sherlouk) [reply Classes/Issues/IssuesViewController.swift]: Pretty sure that's only available from the Notification level, not passed through once you go into an issue. This could be simplified slightly, in hindsight, by just doing `current?.pullRequest` but yh

File: Classes/Utility/AlertAction.swift (hunk 2 above)
Comment (BasThomas) [reply Classes/Utility/AlertAction.swift]: Good point 👍

**Comment by BasThomas** [comment]
Was thinking about this - what about adding the Issue Type as a title / message to the AlertController instead of possibly repeating it in the actions themselves?

**Comment by Sherlouk** [comment]
Wouldn’t be against it! Card it up?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ya! I love that idea

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
